name: Build, publish and deploy docker

on:
  push:
    branches: [ 'main' ]
    tags:
      - 'v*'


env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    name: Build and push
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=tag,enable=${{ startsWith(github.ref, 'refs/tags/v') }}
            type=raw,value=latest,enable=${{ startsWith(github.ref, 'refs/tags/v') }}
            type=raw,value=test,enable=true

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            APP_VERSION=${{ github.ref_name }}

  deploy-testing:
    name: Deploy Testing
    needs: build-and-push-image
    runs-on: [ self-hosted, Linux, testing ]
    environment:
      name: Testing
      url: https://api.test.profcomff.com/userdata
    env:
      API_CONTAINER_NAME: com_profcomff_api_userdata_test
      WORKER_CONTAINER_NAME: com_profcomff_worker_userdata_test
    permissions:
      packages: read

    steps:
      - name: Pull new version
        run: docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:test

      - name: Migrate DB
        run: |
          docker run \
            --rm \
            --network=web \
            --env DB_DSN=${{ secrets.DB_DSN }} \
            --name ${{ env.API_CONTAINER_NAME }}_migration \
            --workdir="/" \
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:test \
            alembic upgrade head

      - name: Run new version API
        id: run_test_api
        run: |
          docker stop ${{ env.API_CONTAINER_NAME }} || true && docker rm ${{ env.API_CONTAINER_NAME }} || true
          docker run \
            --detach \
            --restart always \
            --network=web \
            --env DB_DSN='${{ secrets.DB_DSN }}' \
            --env ROOT_PATH='/userdata' \
            --env AUTH_URL='https://api.test.profcomff.com/auth' \
            --env GUNICORN_CMD_ARGS='--log-config logging_test.conf' \
            --name ${{ env.API_CONTAINER_NAME }} \
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:test

      - name: Run new version worker
        id: run_test_worker
        run: |
          docker stop ${{ env.WORKER_CONTAINER_NAME }} || true && docker rm ${{ env.WORKER_CONTAINER_NAME }} || true
          docker run \
            --detach \
            --restart always \
            --network=kafka \
            --env DB_DSN='${{ secrets.DB_DSN }}' \
            --env KAFKA_DSN='${{ secrets.KAFKA_DSN }}' \
            --env KAFKA_LOGIN='${{ secrets.KAFKA_LOGIN }}' \
            --env KAFKA_PASSWORD='${{ secrets.KAFKA_PASSWORD }}' \
            --env KAFKA_GROUP_ID='${{ vars.KAFKA_GROUP_ID }}' \
            --env KAFKA_TOPICS='${{ vars.KAFKA_TOPICS }}' \
            --name ${{ env.WORKER_CONTAINER_NAME }} \
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:test python -m userdata_api start --instance worker
      

  deploy-production:
    name: Deploy Production
    needs: build-and-push-image
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: [ self-hosted, Linux, production ]
    environment:
      name: Production
      url: https://api.profcomff.com/userdata
    env:
      API_CONTAINER_NAME: com_profcomff_api_userdata
      WORKER_CONTAINER_NAME: com_profcomff_worker_userdata
    permissions:
      packages: read

    steps:
      - name: Pull new version
        run: docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

      - name: Migrate DB
        run: |
          docker run \
            --rm \
            --network=web \
            --env DB_DSN=${{ secrets.DB_DSN }} \
            --name ${{ env.API_CONTAINER_NAME }}_migration \
            --workdir="/" \
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest \
            alembic upgrade head

      - name: Run new version API
        id: run_prod_api
        run: |
          docker stop ${{ env.API_CONTAINER_NAME }} || true && docker rm ${{ env.API_CONTAINER_NAME }} || true
          docker run \
            --detach \
            --restart always \
            --network=web \
            --env DB_DSN='${{ secrets.DB_DSN }}' \
            --env ROOT_PATH='/userdata' \
            --env GUNICORN_CMD_ARGS='--log-config  logging_prod.conf' \
            --env AUTH_URL='https://api.profcomff.com/auth' \
            --name ${{ env.API_CONTAINER_NAME }} \
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

      - name: Run new version worker
        id: run_prod_worker
        run: |
          docker stop ${{ env.WORKER_CONTAINER_NAME }} || true && docker rm ${{ env.WORKER_CONTAINER_NAME }} || true
          docker run \
            --detach \
            --restart always \
            --network=kafka \
            --env DB_DSN='${{ secrets.DB_DSN }}' \
            --env KAFKA_DSN='${{ secrets.KAFKA_DSN }}' \
            --env KAFKA_LOGIN='${{ secrets.KAFKA_LOGIN }}' \
            --env KAFKA_PASSWORD='${{ secrets.KAFKA_PASSWORD }}' \
            --env KAFKA_GROUP_ID='${{ vars.KAFKA_GROUP_ID }}' \
            --env KAFKA_TOPICS='${{ vars.KAFKA_TOPICS }}' \
            --name ${{ env.WORKER_CONTAINER_NAME }} \
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest python -m userdata_api start --instance worker
